apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cd-mriganka-operator
  namespace: openshift-marketplace
spec:
  displayName: Mriganka's Composite Ansible Operator
  publisher: Arch POC
  sourceType: grpc
  image: quay.io/mpaulgreen/mrigankacatalog:v0.0.1
  updateStrategy:
    registryPoll:
      interval: 1m
